<?php
/**
 * Add returns button to order - essentially goes to contact page and prefills info
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author 		 Chris Rogers
 * @since 		 2016-01-22
 */
?>
<div class="order-action-buttons">
	<?php  $_order = $this->getOrder() ?>
	<?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
	    <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="button link-rss f-none">
	    	<?php echo $this->__('Subscribe to Order Status') ?>
	    </a>
	<?php endif; ?>
	<?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
	    <a href="<?php echo $this->getReorderUrl($_order) ?>" class="button link-reorder">
	    	<?php echo $this->__('Reorder') ?>
	    </a>
	<?php endif ?>
	<a href="<?php echo $this->getPrintUrl($_order) ?>" class="button link-print" onclick="this.target='_blank';">
		<?php echo $this->__('Print Order') ?>
	</a>
	<?php if ($this->helper('sales/reorder')->canReorder($_order) && $_order->getStatus() !== "canceled" && $_order->getGrandTotal() != 0) : ?>
		<a href="<?php echo Mage::getUrl('contact-us?o='.$_order->getIncrementId()) ?>" class="link-returns button">
			<?php echo $this->__('Request Refund') ?>
		</a>
	<?php endif; ?>
	<?php echo $this->getChildHtml(); ?>
</div>