<?php
/**
 * Adding support for Google analytics - abandoned shopping cart rates
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2014 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Chris Rogers
 * @since       2016-01-31
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout_rwd.js') ?>"></script>
<ol class="opc opc-firststep-<?php echo $this->getActiveStep() ?>" id="checkoutSteps">
    <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
        <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
        <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
            <div class="step-title">
                <span class="number"><?php echo $i ?></span>
                <h2><?php echo $_stepInfo['label'] ?></h2>
                <a href="#"><?php echo $this->__('Edit') ?></a>
            </div>
            <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
                <?php echo $this->getChildHtml($_stepId) ?>
            </div>
        </li>
    <?php endforeach ?>
</ol>
<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );

    /**
    * Start Google analytics integration
    */
    Checkout.prototype.gotoSection = function(section, reloadProgressBlock) 
    {
        // Adds class so that the page can be styled to only show the "Checkout Method" step
        if ((this.currentStep == 'login' || this.currentStep == 'billing') && section == 'billing') {
            $j('body').addClass('opc-has-progressed-from-login');
        }

        if (reloadProgressBlock) {
            this.reloadProgressBlock(this.currentStep);
        }

        // Checkout abandonment rate analytics - Credit to Inchoo
        try {
            var step = 0;
            var option = '';
            switch (section) {
                case 'onepage':
                case 'login':
                    step = 2;
                    option = 'Checkout intro';
                break;
                case 'billing':
                    step = 3;
                    option = 'Checkout billing';
                break;
                case 'shipping':
                    step = 4;
                    option = 'Checkout shipping';
                break;
                case 'shipping_method':
                    step = 5;
                    option = 'Checkout shipping method';
                break;
                case 'payment':
                    step = 6;
                    option = 'Checkout payment method';
                break;
                case 'review':
                    step = 7;
                    option = 'Checkout review';
                break;
            }
            ga('send', 'pageview', '/checkout/onepage/' + section + '/');
            ga('send', 'event', 'Checkout', option);
            ga('require', 'ec');
            ga('ec:setAction', 'checkout', {'step': step, 'option': option});

        } catch (err) {
            console.log(err);
        }

        this.currentStep = section;
        var sectionElement = $('opc-' + section);
        sectionElement.addClassName('allow');
        this.accordion.openSection('opc-' + section);

        // Scroll viewport to top of checkout steps for smaller viewports
        if (Modernizr.mq('(max-width: ' + bp.xsmall + 'px)')) {
            $j('html,body').animate({scrollTop: $j('#checkoutSteps').offset().top}, 800);
        }

        if (!reloadProgressBlock) {
            this.resetPreviousSteps();
        }

        try {
            ga('require', 'ec');
            <?php if ($currentStep == "login"): ?>
                ga('send', 'pageview', '/checkout/onepage/login/');
                ga('send', 'event', 'Checkout', 'Intro');
                ga('ec:setAction', 'checkout', {'step': 2, 'option': 'Checkout intro'});
            <?php elseif ($currentStep == "billing"): ?>
                ga('send', 'pageview', '/checkout/onepage/billing/');
                ga('send', 'event', 'Checkout', 'Billing');
                ga('ec:setAction', 'checkout', {'step': 3, 'option': 'Billing address'});
            <?php endif; ?>
        } catch (err) {
            console.log(err);
        }
    };
//]]>
</script>
