<?php 
/**
 *
 * @author 	Chris Rogers <chris@portchris.co.uk>
 * @since 	2019-01-11 <1.0.0>
 * @var 	NaturalRemedyCo_FaceAndFigure_Block_Header 	$this
 */
?>
<script type="text/javascript">
	window.config = (window.config != null) ? window.config : {};
	window.config.header = <?= $this->getBlockConfig(); ?>;
	require.config({
		paths: {
			"header": "<?= $this->getReactComponent() ?>"
		}
	});
</script>
