#! /bin/bash
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Edit/Tab/Configuration.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-7.0.2-7.1.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-7.0.1-7.0.2.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-7.3.0-8.0.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.4.2-5.4.3.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-7.2.0-7.3.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.4.1-5.4.2.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-9.0.1-9.0.2.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-9.1.1-9.3.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.4.3-5.5.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-9.3.1-9.3.2.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.4.0-5.4.1.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-9.3.2-9.4.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.5.0-5.5.1.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-9.3.0-9.3.1.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-9.0.0-9.0.1.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.5.1-5.5.2.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.7.2-5.7.3.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-9.1.0-9.1.1.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.6.0-5.7.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-8.0.0-8.1.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.5.2-5.6.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.7.3-5.7.4.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.0.0-5.1.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-6.0.0-6.1.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-9.0.2-9.1.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-8.1.0-9.0.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.7.1-5.7.2.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.2.0-5.3.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.7.4-6.0.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.7.0-5.7.1.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-7.1.0-7.2.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.3.0-5.4.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-5.1.0-5.2.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-7.0.0-7.0.1.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-6.1.1-7.0.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-upgrade-6.1.0-6.1.1.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Edit/Tab/Categories.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Edit/Tab/Filters.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/controllers/Adminhtml/SimplegoogleshoppingController.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Renderer/Action.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Renderer/Status.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup/mysql4-install-5.0.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Edit/Tab/Cron.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Renderer/Link.php
rm ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field/Extensions.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Edit/Form.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Edit/Tabs.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Model/Resource/Simplegoogleshopping/Collection.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Renderer
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/System/Config/Form/Field/Link.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Edit/Tab
rm ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field/Link.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/controllers/SimplegoogleshoppingController.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Grid.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Edit.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping/Edit
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/System/Config/Form/Field
rm ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config/Form/Field/Link.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System/Config/Form/Field/Cron.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Simplegoogleshopping.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Model/Resource/Simplegoogleshopping.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Model/Resource/Simplegoogleshopping
rm ./app/design/adminhtml/default/default/template/simplegoogleshopping/categories.phtml
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config/Form/Field
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/System/Config/Form
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form
rm ./app/design/adminhtml/default/default/template/simplegoogleshopping/filters.phtml
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System/Config/Form/Field
rm ./app/code/community/Wyomind/Watchlog/controllers/Adminhtml/AdvancedController.php
rm ./app/code/community/Wyomind/Watchlog/sql/watchlog_setup/mysql4-install-1.0.0.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Model/System/Config/Source/Urls.php
rm ./app/design/adminhtml/default/default/template/simplegoogleshopping/empty.phtml
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/sql/simplegoogleshopping_setup
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/System/Config
rm ./app/design/adminhtml/default/default/template/simplegoogleshopping/cron.phtml
rm ./app/code/community/Wyomind/Watchlog/controllers/Adminhtml/BasicController.php
rm ./skin/adminhtml/default/default/simplegoogleshopping/simplegoogleshopping.css
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config/Form
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config
rm ./skin/adminhtml/default/default/simplegoogleshopping/simplegoogleshopping.js
rm ./app/code/local/Wyomind/Simplegoogleshopping/Helper/Simplegoogleshopping.php
rm ./app/code/local/Wyomind/Licensemanager/controllers/ActivationController.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Simplegoogleshopping.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Model/System/Config/Source
rm ./app/code/local/Wyomind/Simplegoogleshopping/Model/Simplegoogleshopping.php
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System/Config/Form
rm ./app/design/adminhtml/default/default/template/watchlog/email/report.phtml
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Taxonomy.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Model/Product/Collection.php
rm ./app/code/community/Wyomind/Watchlog/Model/Mysql4/Watchlog/Collection.php
rm ./app/code/community/Wyomind/Watchlog/Model/System/Config/Source/Link.php
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Renderer/Status.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Updater.php
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Library.php
rm ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/Notifications.php
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Sample.php
rmdir  ./app/design/adminhtml/default/default/template/simplegoogleshopping
rm ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/Report.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml/System
rm ./app/design/adminhtml/default/default/template/watchlog/advanced.phtml
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Advanced/Grid.php
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System/Config
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/controllers/Adminhtml
rm ./app/design/adminhtml/default/default/layout/simplegoogleshopping.xml
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Renderer/Ip.php
rm ./app/code/local/Wyomind/Notificationmanager/Model/Resource/Setup.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Model/System/Config
rm ./skin/adminhtml/default/default/simplegoogleshopping/ajax-loader.gif
rm ./skin/adminhtml/default/default/simplegoogleshopping/AutoComplete.js
rm ./app/design/adminhtml/default/default/template/watchlog/basic.phtml
rm ./skin/adminhtml/default/default/simplegoogleshopping/treeview_p.png
rmdir  ./app/code/community/Wyomind/Watchlog/Model/System/Config/Source
rm ./skin/adminhtml/default/default/simplegoogleshopping/treeview_m.png
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Basic/Grid.php
rm ./app/design/adminhtml/default/default/template/watchlog/chart.phtml
rmdir  ./app/design/adminhtml/default/default/template/watchlog/email
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Advanced
rm ./app/code/local/Wyomind/Simplegoogleshopping/etc/jstranslator.xml
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Advanced.php
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Renderer
rm ./app/code/local/Wyomind/Licensemanager/Helper/Licensemanager.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block/Adminhtml
rm ./app/design/adminhtml/default/default/layout/licensemanager.xml
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Model/Resource
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System
rm ./app/code/local/Wyomind/Simplegoogleshopping/Model/Observer.php
rm ./skin/adminhtml/default/default/simplegoogleshopping/updater.js
rm ./app/code/local/Wyomind/Notificationmanager/Model/Observer.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Resource
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Model/Product
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Basic
rmdir  ./app/code/community/Wyomind/Watchlog/controllers/Adminhtml
rm ./skin/adminhtml/default/default/CodeMirror2/lib/codemirror.css
rmdir  ./app/code/community/Wyomind/Watchlog/Model/Mysql4/Watchlog
rm ./skin/adminhtml/default/default/simplegoogleshopping/arrow.png
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Chart.php
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Basic.php
rm ./app/code/community/Wyomind/Watchlog/Model/Mysql4/Watchlog.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Model/System
rm ./skin/adminhtml/default/default/CodeMirror2/theme/default.css
rm ./skin/adminhtml/default/default/CodeMirror2/lib/codemirror.js
rm ./app/code/local/Wyomind/Notificationmanager/etc/adminhtml.xml
rmdir  ./app/code/community/Wyomind/Watchlog/Model/System/Config
rm ./app/code/local/Wyomind/Simplegoogleshopping/Helper/Data.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/controllers
rm ./app/code/local/Wyomind/Simplegoogleshopping/etc/system.xml
rmdir  ./app/design/adminhtml/default/default/template/watchlog
rmdir  ./app/code/community/Wyomind/Watchlog/sql/watchlog_setup
rm ./app/code/local/Wyomind/Notificationmanager/Helper/Data.php
rm ./skin/adminhtml/default/default/CodeMirror2/mode/xml/xml.js
rm ./app/code/local/Wyomind/Simplegoogleshopping/etc/config.xml
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml
rm ./skin/adminhtml/default/default/CodeMirror2/lib/runmode.js
rm ./skin/adminhtml/default/default/CodeMirror2/lib/overlay.js
rm ./app/code/local/Wyomind/Notificationmanager/etc/system.xml
rm ./app/code/local/Wyomind/Notificationmanager/etc/config.xml
rm ./app/code/local/Wyomind/Licensemanager/Model/Observer.php
rm ./app/design/adminhtml/default/default/layout/watchlog.xml
rmdir  ./skin/adminhtml/default/default/simplegoogleshopping
rmdir  ./skin/adminhtml/default/default/CodeMirror2/mode/xml
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml
rm ./app/code/community/Wyomind/Watchlog/Model/Watchlog.php
rm ./app/code/community/Wyomind/Watchlog/Model/Observer.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Helper
rmdir  ./app/code/local/Wyomind/Notificationmanager/Helper
rmdir  ./app/code/local/Wyomind/Licensemanager/controllers
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Block
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/Model
rm ./app/code/local/Wyomind/Licensemanager/Helper/Data.php
rmdir  ./skin/adminhtml/default/default/CodeMirror2/theme
rm ./app/code/local/Wyomind/Licensemanager/etc/config.xml
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model
rmdir  ./app/code/community/Wyomind/Watchlog/Model/System
rm ./app/locale/en_US/template/email/watchlog_report.html
rmdir  ./app/code/community/Wyomind/Watchlog/Model/Mysql4
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/etc
rm ./app/code/community/Wyomind/Watchlog/Helper/Data.php
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping/sql
rmdir  ./skin/adminhtml/default/default/CodeMirror2/mode
rmdir  ./app/code/community/Wyomind/Watchlog/controllers
rm ./app/code/community/Wyomind/Watchlog/etc/config.xml
rmdir  ./app/code/local/Wyomind/Notificationmanager/etc
rmdir  ./skin/adminhtml/default/default/CodeMirror2/lib
rm ./app/code/community/Wyomind/Watchlog/etc/system.xml
rm ./skin/adminhtml/default/default/CodeMirror2/LICENSE
rmdir  ./app/design/adminhtml/default/default/template
rm ./lib/Wyomind/Google/Taxonomies/[default]_en_US.txt
rm ./app/locale/fr_FR/Wyomind_Simplegoogleshopping.csv
rm ./app/locale/de_DE/Wyomind_Simplegoogleshopping.csv
rm ./app/locale/nl_NL/Wyomind_Simplegoogleshopping.csv
rm ./app/etc/modules/Wyomind_Simplegoogleshopping.xml
rmdir  ./app/code/local/Wyomind/Licensemanager/Helper
rmdir  ./app/design/adminhtml/default/default/layout
rmdir  ./app/code/local/Wyomind/Licensemanager/Block
rmdir  ./app/code/local/Wyomind/Simplegoogleshopping
rm ./app/etc/modules/Wyomind_Notificationmanager.xml
rmdir  ./app/code/local/Wyomind/Licensemanager/Model
rmdir  ./skin/adminhtml/default/default/CodeMirror2
rmdir  ./app/code/community/Wyomind/Watchlog/Helper
rmdir  ./app/code/local/Wyomind/Notificationmanager
rmdir  ./app/code/local/Wyomind/Licensemanager/etc
rmdir  ./app/code/community/Wyomind/Watchlog/Block
rmdir  ./app/code/community/Wyomind/Watchlog/Model
rmdir  ./app/code/community/Wyomind/Watchlog/sql
rmdir  ./app/code/community/Wyomind/Watchlog/etc
rm ./app/etc/modules/Wyomind_Licensemanager.xml
rmdir  ./app/code/local/Wyomind/Licensemanager
rmdir  ./app/design/adminhtml/default/default
rmdir  ./app/code/community/Wyomind/Watchlog
rm ./lib/Wyomind/Google/Taxonomies/it_IT.txt
rm ./lib/Wyomind/Google/Taxonomies/de_DE.txt
rm ./lib/Wyomind/Google/Taxonomies/en_AU.txt
rm ./lib/Wyomind/Google/Taxonomies/fr_FR.txt
rm ./lib/Wyomind/Google/Taxonomies/es_ES.txt
rm ./lib/Wyomind/Google/Taxonomies/nl_NL.txt
rm ./lib/Wyomind/Google/Taxonomies/en_GB.txt
rm ./app/etc/modules/Wyomind_Watchlog.xml
rmdir  ./app/locale/en_US/template/email
rm ./lib/Wyomind/Google/Requirements.php
rmdir  ./skin/adminhtml/default/default
rmdir  ./lib/Wyomind/Google/Taxonomies
rmdir  ./app/design/adminhtml/default
rmdir  ./app/code/community/Wyomind
rmdir  ./app/locale/en_US/template
rmdir  ./app/code/local/Wyomind
rmdir  ./skin/adminhtml/default
rmdir  ./app/design/adminhtml
rmdir  ./lib/Wyomind/Google
rmdir  ./app/code/community
rm ./var/tmp/sgs/sgs_1.flag
rmdir  ./app/locale/en_US
rmdir  ./app/locale/fr_FR
rmdir  ./app/locale/de_DE
rmdir  ./app/locale/nl_NL
rmdir  ./app/etc/modules
rmdir  ./skin/adminhtml
rmdir  ./app/code/local
rmdir  ./var/tmp/sgs
rmdir  ./lib/Wyomind
rmdir  ./app/design
rmdir  ./app/locale
rmdir  ./app/code
rmdir  ./app/etc
rm ./LICENSE.TXT
rmdir  ./var/tmp
rmdir  ./skin
rmdir  ./var
rmdir  ./lib
rmdir  ./app