<html>
<head>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h1>Your token was successfully saved</h1>
                <form method="post"
                      action="<?php echo $this->urlEscape($this->getUrl('square_magento/index/saveLocation')); ?>"
                      enctype="multipart/form-data">
                    <input name="form_key"
                           type="hidden"
                           value="<?php echo $this->htmlEscape(Mage::getSingleton('core/session')->getFormKey()); ?>" />
                    <div class="form-group">
                        <?php $locations = $this->getLocations(); ?>
                        <label for="location">
                            <?php echo $this->htmlEscape($this->__('Please select a default location')); ?>
                        </label>
                        <select name="location" id="location" class="form-control">
                            <?php foreach ($locations as $location): ?>
                                <option value="<?php echo $this->htmlEscape($location->getSquareId()); ?>">
                                    <?php echo $this->htmlEscape($location->getName()); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit"
                               class="btn btn-info"
                               value="<?php echo $this->htmlEscape($this->__('Save')); ?>" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>