<?php 
/**
 * Wufoo contact form
 * @author 	Chris Rogers <chris@portchris.co.uk>
 * @since 	2019-01-11 <1.0.0>
 */
?>
<form id="contactForm" name="form2" class="wufoo topLabel page" accept-charset="UTF-8" autocomplete="off"
	enctype="multipart/form-data" method="post" novalidate
	action="https://portchris.wufoo.com/forms/m1ks8qpu02enbgh/#public">
	<ul class="form-list">
		<li id="foli4" data-wufoo-field data-field-type="text" class="notranslate form-group fields">
			<label class="desc" id="title4" for="Field4">
				Name
				<span id="req_4" class="req">*</span>
			</label>
			<div class="vspace-xs">
				<input id="Field4" name="Field4" type="text" class="form-control field text medium validate-no-html-tags validate-alphanum-with-spaces required-entry" value="" maxlength="255"
					tabindex="1" onkeyup="" required placeholder="Your full name so we know who you are" />
			</div>
		</li>
		<li id="foli5" class="notranslate form-group fields">
			<label class="desc" id="title5" for="Field5">
				Email
				<span id="req_5" class="req">*</span>
			</label>
			<div class="vspace-xs">
				<input id="Field5" name="Field5" type="email" spellcheck="false" class="form-control field text medium validate-no-html-tags validate-email required-entry" value=""
					maxlength="255" tabindex="2" placeholder="Your e-mail address so that we may respond to you"
					required />
			</div>
		</li>
		<li id="foli7" class="notranslate form-group fields">
			<label class="desc " id="title7" for="Field7">
				Phone Number (optional)
			</label>
			<div class="vspace-xs">
				<input id="Field7" name="Field7" type="text" class="form-control field text nospin medium validate-no-html-tags validate-phoneLax" value="" tabindex="3"
					onkeyup="" placeholder="Your phone number if you wish us to call you" />
			</div>
		</li>
		<li id="foli3" class="notranslate form-group fields">
			<label class="desc" id="title3" for="Field3">
				Your message
				<span id="req_3" class="req">*</span>
			</label>
			<div class="vspace-xs">
				<textarea id="Field3" name="Field3" class="form-control field textarea medium validate-no-html-tags required-entry " spellcheck="true" rows="10" cols="50"
					tabindex="4" onkeyup="" placeholder="" required></textarea>
			</div>
		</li>
		<li class="buttons">
			<div class="vspace-xs">
				<input id="saveForm" name="saveForm" class="button btTxt submit btn btn-primary" type="submit"
					value="Submit" />
			</div>
		</li>
		<li class="hidden hide sr-only">
			<label for="comment">Do Not Fill This Out</label>
			<textarea name="comment" id="comment" rows="1" cols="1"></textarea>
			<input type="hidden" id="idstamp" name="idstamp" value="2H/bjhTx9SgpbuOOQfjTwelCo6OhloACmsolDegE/Ug=" />
		</li>
	</ul>
</form>
<script type="text/javascript">
//<![CDATA[
    var theForm = new VarienForm('contactForm', true);
//]]>   
</script>