<?php
/**
 * @author      Chris Rogers
 * @package     rwd_hannasherbs_default
 * @since       2015-06-12
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>

<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="en" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" id="top" class="no-js"> <!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container">
            <div class="main">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php // This left_first block will display above the main content on smaller viewports ?>
                <div class="col2-set">
                    <div class="col-1">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-info')->toHtml(); ?>
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_contact')->toHtml(); ?>
                        <div class="vspace">
                            <?php echo $this->getChildHtml('content') ?>
                        </div>
                    </div>
                    <div class="col-2">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-map')->toHtml(); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
