<?php
/**
 * @category    design
 * @package     rwd_hannasherbs default
 * @author      Chris Rogers
 * @since       2015-06-05
 */
?>

<div class="header-language-background">
    <div class="header-language-container">
        <div class="store-language-container">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>

        <?php echo $this->getChildHtml('currency_switcher') ?>
        
        <!-- Account Dropdown -->
        <div id="header-top-account" class="hspace-xs">
            <a href="#header-account-dropdown" class="skip-link skip-account">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Account'); ?></span>
            </a>
            <div id="header-account-dropdown" class="skip-content">
                <?php echo $this->getChildHtml('topLinks') ?>
            </div>
        </div>
        
        <!-- Cart -->
        <div id="header-top-cart" class="hspace-xs">
            <a href="#header-nav" class="skip-link skip-nav">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Menu'); ?></span>
            </a>
            <div class="header-minicart">
                <?php echo $this->getChildHtml('minicart_head'); ?>
            </div>
        </div>
        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top_header_links')->toHtml(); ?> 
    </div>
</div>

<header id="header" class="page-header">
    <div class="page-header-container">
        <a class="logo" href="<?php echo $this->getUrl('') ?>">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
            <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
        </a>

        <!-- Search -->
        <div id="header-search" class="skip-content">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>

        <?php // In order for the language switcher to display next to logo on smaller viewports, it will be moved here.
              // See app.js for details ?>
        <div class="store-language-container"></div>

        <!-- Skip Links -->

        <div class="skip-links">
            <a href="#header-nav" class="skip-link skip-nav">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Menu'); ?></span>
            </a>

            <!-- Search -->
            <a href="#header-search-mobile" class="skip-link skip-search">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Search'); ?></span>
            </a>

            <!-- Account -->
            <a href="#header-account" class="skip-link skip-account skip-mobile">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Account'); ?></span>
            </a>

            <!-- Cart -->
            <div class="header-minicart skip-mobile">
                <?php echo $this->getChildHtml('minicart_head_mobile'); ?>
            </div>
        </div>

        <!-- Account -->
        <div id="header-account" class="skip-content">
            <?php echo $this->getChildHtml('topLinks') ?>
        </div>

        <!-- Search -->
        <div id="header-search-mobile" class="skip-content">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>

        <!-- Cart -->
        <div id="header-cart-mobile" class="block block-cart skip-content hpadding-xs vpadding-xs">
            <?php echo $this->getChildHtml('minicart_content');?>
        </div>
        <!-- <div id="header-cart" class="skip-content">
            <div class="mini-cart">
                <div class="menu-wrapper">
                    <div class="menu cart-menu">
                        <div class="empty">Your cart is empty.</div>
                    </div>
                </div>
            </div>
        </div> -->
    </div>

    <!-- Navigation -->

    <div id="header-nav" class="skip-content">
        <?php echo $this->getChildHtml('topMenu') ?>
    </div>
</header>


<?php echo $this->getChildHtml('topContainer'); ?>
