<?php /** @var Ess_M2eProUpdater_Block_Adminhtml_HelpBlock $this */ ?>

<div
    id="<?php echo $this->getId(); ?>"
    class="block_notices <?php echo $this->getClass(); ?>"
    <?php if ($this->hasStyle()): ?>style="<?php echo $this->getStyle(); ?>"<?php endif; ?>
>
    <div class="help_block_content" style="display: block;">
        <?php echo $this->getContent(); ?>
    </div>
</div>